name: Playwright Cucumber Framework

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Debug Features
        run: |
          find . -name "*.feature"
          grep -R "@regression" tests/features || true
          grep -R "@smoke" tests/features || true

      - name: Run Smoke Tests
        if: github.event_name == 'pull_request'
        run: npm run smoke

      - name: Run Regression Tests
        if: github.event_name != 'pull_request'
        run: npm run regression

      - name: Rerun Failed Tests
        if: failure()
        run: npm run rerun

      - name: Generate Allure Report
        if: always()
        run: npm run report

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-report
          path: |
            reports/
            allure-report/